ndlib/marble-website-starter

README.md
__mocks__/file-mock.js
__mocks__/gatsby.js
jest-enzyme-setup.js
jest-preprocess.js
jest.config.js
loadershim.js
package.json
src/components/Layout/PageWrapper/Footer/index.js
src/components/Layout/PageWrapper/Footer/style.module.css
src/components/Layout/PageWrapper/Footer/test.js
yarn.lock

1.  Added the jest + enzyme tests 
2. One example of dealing with the static query object in testing
3. yarn watch. 
4. yarn build now runs tests first 
As a side note, it is probably a good idea to be in the habit of using yarn + cmd rather than gatsby + cmd. 
Also most existing tests should mostly work.

Add jest and an example test

---

src/components/APIViews/Search/SearchDisplay/PageNum/PaginationButton/index.js
src/components/APIViews/Search/SearchDisplay/PageNum/index.js
src/components/APIViews/Search/SearchDisplay/PerPage/index.js
src/components/APIViews/Search/SearchDisplay/index.js
src/components/APIViews/Search/index.js
src/components/ManifestViews/UniversalViewer/UniversalViewerLayout/index.js
src/components/ManifestViews/UniversalViewer/index.js
src/components/Shared/SearchBox/SearchButton/index.js
src/components/Shared/SearchBox/SearchField/index.js
src/components/Shared/SearchBox/index.js
src/pages/search.js
src/pages/viewer.js

During static build time `window` is undefined. We are mostly using `window.location` in hydrated components, but this is a safer approach.

Replace window.location with location

---

src/components/APIViews/Search/SearchDisplay/PageNum/PaginationButton/index.js
src/components/Layout/PageWrapper/BrandingHeader/LinkedLogo/index.js
src/components/Layout/PageWrapper/NavigationHeader/LoginButton/index.js
src/components/Layout/PageWrapper/NavigationHeader/SiteLogo/index.js
src/components/ManifestViews/Item/ItemAside/ImageSection/index.js
src/components/Shared/Breadcrumb/index.js
src/components/Shared/Link/index.js
src/components/Shared/Navigation/index.js
src/components/Shared/SearchBox/index.js

`Link` cannot handle external links. We sometimes do not know if the link we are providing will be external, especially if it is in a nested component like `Card` or a list of navigation links.

Create smart Link

---

package.json

Very helpful for this:
https://atom.io/packages/coverage-markers

Change default of `yarn watch` to also update coverage report locally

---

src/components/ManifestViews/Item/ItemAside/ImageSection/ItemAlternateViews/AlternateImage/AlternateOverlay/index.js
src/components/ManifestViews/Item/ItemAside/ImageSection/ItemAlternateViews/AlternateImage/AlternateOverlay/test.js
src/components/ManifestViews/Item/ItemAside/ImageSection/ItemAlternateViews/AlternateImage/test.js
src/components/ManifestViews/Item/ItemAside/ImageSection/ItemAlternateViews/index.js
src/components/ManifestViews/Item/ItemAside/ImageSection/ItemAlternateViews/test.js
src/components/ManifestViews/Item/ItemAside/ImageSection/index.js
src/components/ManifestViews/Item/ItemAside/ImageSection/test.js
src/components/ManifestViews/Item/ItemAside/index.js
src/components/ManifestViews/Item/ItemAside/test.js
src/components/ManifestViews/Item/ItemPreMain/test.js
src/components/ManifestViews/Item/index.js
src/components/ManifestViews/Item/test.js
src/components/Shared/ActionButtonGroup/index.js
src/components/Shared/ActionButtonGroup/test.js

* MEL-387 - Fix navigating between items losing overlay for additional images on Item page. (Also start additional images at index of 1 so we're not showing the first image twice.)
* MEL-388 - Move action buttons above image on Item page.
* MEL-389 - Move IIIF icon to last place in Action Button group. (Also reordered other icons left to right in terms of what is most common action).
* MEL-385 - "Description, rights/license does not appear on the metadata list outside of the viewer" - Description was already added in this version. License field appears to be html, and is now being set as such.

Item Page enhancements

---

src/components/ManifestViews/Item/ItemAside/ImageSection/ItemAlternateViews/AlternateImage/index.js
src/components/ManifestViews/Item/ItemAside/ImageSection/ItemAlternateViews/AlternateImage/test.js
src/components/ManifestViews/Item/ItemAside/ImageSection/ItemAlternateViews/index.js
src/components/ManifestViews/Item/ItemAside/ImageSection/ItemAlternateViews/test.js
src/components/ManifestViews/Item/ItemAside/ImageSection/index.js
src/components/ManifestViews/Item/ItemAside/ImageSection/test.js
src/components/ManifestViews/Item/ItemAside/index.js
src/components/ManifestViews/Item/ItemAside/test.js
src/components/ManifestViews/Item/index.js
src/components/ManifestViews/UniversalViewer/UniversalViewerLayout/BackToItem/index.js
src/components/ManifestViews/UniversalViewer/UniversalViewerLayout/BackToItem/style.module.css
src/components/ManifestViews/UniversalViewer/UniversalViewerLayout/BackToItem/test.js
src/components/ManifestViews/UniversalViewer/UniversalViewerLayout/index.js
src/components/Shared/Card/index.js
src/components/Shared/ReturnToSearch/index.js
src/utils/__tests__/test.buildReferalState.js
src/utils/buildReferalState.js

Added link based on referring item to Universal viewer. A couple of notes:
* Universal viewer UI changes at 800px, so there is not a good place to put the link. so it is hidden with CSS at viewport widths below 800px.
* The link is based on the referring Item page (sent by Link's location state), so going directly to the UV from say a Google search or doing a hard page refresh will not display the link. I think this is the correct behavior at present as there is the potential to view a manifest in the UV that does not have a corresponding item page. If we can refactor the UV page to be statically built, we should consider refactoring to generate the link from the manifest data instead.

MEL-425 Back button on Universal Viewer

---

gatsby-config.js
src/components/ManifestViews/Collection/index.js
src/components/Search/SearchPreMain/index.js
src/components/Search/SearchPreMain/style.module.css
src/components/Search/SearchPreMain/test.js
src/components/Search/SearchResults/index.js
src/components/Search/SearchTools/index.js
src/components/Search/SearchTools/test.js
src/components/Search/index.js
src/components/Search/test.js
src/components/Shared/DisplayViewToggle/index.js
src/pages/search-new.js

* Add grid/list display toggle to new Search page
* Start to componentize new Search page
* Some unit tests, because why not?
* Move search base information into `gatsby-config.js`

MEL-419 Grid/List view in new search results page

---

content/markdown/about.md
content/markdown/layoutTest.md
gatsby-node.js
package.json
src/components/Markdown/availableComponents.js
src/components/MiradorViewerPage/MiradorWrapper/index.js
src/components/MiradorViewerPage/index.js
src/components/Shared/MiradorViewer/index.js
src/templates/markdownTemplate.js
src/templates/mirador.js
yarn.lock

* This is sort of broken with the way we have manifests building, but will get sorted out after I merge in @jonhartzler's changes and fix things.
* Basically, we check the markdown files at page creation time, and if they have a iiifJson field, we also build another page at a similar path adding `/mirador` to the end.
* Also create an ifram of the mirador page as component that can be placed on a page (Mirador is pretty agressive about taking over everything, so an iframe keeps it safe for now).
TODO:
* tests
* fix stuff up with the new importer after merging in changes.

MEL-472 Add Mirador

---

content/configuration.js
gatsby-config.js
gatsby-node.js
src/components/Layout/PageWrapper/BrandingHeader/index.js
src/components/Layout/PageWrapper/BrandingHeader/test.js

* Provide option to remove brand bar in `Site.SiteMetaData` and respect that option in the BrandingHeader component.
* Set `useBrandBar: false` in `configuration.js` .
* Add some typeDefs to predefine some GraphQL stuff we're expecting to use.

MEL-499 Remove Branding Bar

---

@ndlib/gatsby-theme-marble/src/components/App/Pages/Portfolio/PortfolioBody/PortfolioEdit/EditItems/EditItem/EditItemForm/EditItemFormContent/index.js
@ndlib/gatsby-theme-marble/src/components/Internal/MaterialButton/style.module.css
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/style.module.css

* Bookmarking menu was added in previous PR. This adds the ability to 
create a new portfolio from this menu, and displays a message when the 
user does not have any existing portfolios.
* It also sorts the portfolios in the bookmarking menu in a consistent way now.
* Disabling some edit features on individual item edit.

MARBLE-698 Enhance Bookmarking menu

---

@ndlib/gatsby-theme-marble/src/assets/icons/svg/mirador-24px.svg
@ndlib/gatsby-theme-marble/src/pages/all.js
site/content/menus.js
site/src/pages/sitemap.js

* Add basic `Layout` wrapper and styling.
* Move url to `/sitemap` from `/all`
* Display `collections`, `items`, `browse pages`, and "other things" in separate sections.
* add mirador links to items
* move code to `/site`
* add link to `/sitemap` in footer

Change all page to be more like a sitemap

---

scripts/gatsby-source-iiif/src/realDatesFromCatalogedDates/index.js
scripts/gatsby-source-iiif/src/realDatesFromCatalogedDates/test.js

library dates actually have things like 
'[19--?].'  in them.

fix bug with extra characters on library dates

---

@ndlib/gatsby-theme-marble/package.json
@ndlib/gatsby-theme-marble/src/components/Internal/ActionModal/index.js
@ndlib/gatsby-theme-marble/src/components/Internal/ActionModal/sx.js
@ndlib/gatsby-theme-marble/src/components/Internal/Seo/SeoContent/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/Copyright/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/Copyright/sx.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadCitation/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadImage/ImagePager/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadImage/ImagePager/test.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadImage/ImagePreview/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadImage/ImagePreview/test.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadImage/ImageSettings/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadImage/ImageSettings/test.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadImage/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadImage/sx.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadImage/test.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadImage/utils.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadMetadata/AboutIIIF/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadMetadata/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/sx.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/test.js
@ndlib/gatsby-theme-marble/src/templates/markdownTemplate.js
@ndlib/gatsby-theme-marble/src/utils/download.js
site/content/markdown/browse.md
site/src/@ndlib/gatsby-theme-marble/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/Copyright/index.js
site/src/@ndlib/gatsby-theme-marble/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadMetadata/AboutIIIF/index.js
yarn.lock

* Image download:
* Image preview
* Pager to select image if there are multiple
* Image download size and format options
* Disabled download when item has no images or if under copyright.
* Metadata download:
* Description of IIIF and links to more information
* Direct download for IIIF manifest file
* Stub component for Citation
* Adds `js-file-downloader` run `yarn` after pulling.
One image:
Multiple Images for item:
Collections of multiple items:
Copyrighted image:

MARBLE-836 Add Download UI

---

scripts/gatsby-source-iiif/indexSearch.js

The problem seems to be that the index is assessing date as an integer field when it is a string sometimes with "ca. 1600". so try to tell the index it is a string.

attempt fix the error in the indexing.

---

@ndlib/gatsby-theme-marble/src/components/Layout/index.js
site/content/markdown/browse.md
site/src/@ndlib/gatsby-theme-marble/components/Pages/IndexPage/index.js

**Reported problem:**
Going to `/browse` works fine, but going to `/browse#date` caused page 
to become unresponsive and links would not work.
**Observed problem:**
Going to `/browse#date` caused page to hang and an infinite loop was 
triggered by Okta Auth library being unable to read the cookie.
**Actual problem and solution:**
Due to the way Gatsby and Reach Router handle urls internally, there was 
a conflict with the Okta Auth library causing the Okta Auth library to 
receive incorrect information about the referring url. Since hash urls 
can be problematic in SPA and Gatsby apps and are rarely used in our 
current setup, I've opted to replace links of the format `/browse#date` 
with `/browse?scrollto=date` and add a conditional check on the `Layout` 
component to handle targeting …

MARBLE-876 Bugfix Browse page with url hash

---

@ndlib/gatsby-theme-marble/src/components/App/Pages/Portfolio/index.js
@ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserBasePath/UserBasePathContent/index.js
@ndlib/gatsby-theme-marble/src/store/actions/loginActions/index.js
@ndlib/gatsby-theme-marble/src/store/reducers/loginReducer/index.js

* Rework reducer a little bit so we can differentiate between someone whom we have not checked to see if they are logged in and someone who is not actually logged in.
* Reduce repeated api calls when we don't have a full picture of the user on portfolio pages.

MARBLE-827 Fix loading to not show error pages

---

scripts/codebuild/pre_build.sh

Basically add a bash trap to trap the following errors.
It then increments the error counter to decide if it should exit later.

Fix tests to have both run

---

.travis.yml
@ndlib/gatsby-theme-marble/src/components/Pages/MiradorViewer/index.js
scripts/gatsby-source-iiif/getSchema.js
site/src/pages/sitemap.js

* Fix bad graphQL on sitemap page
* Fix call to undefined `window` on Mirador pages
* Update `getSchema.js` to use the Travis list of ids
* Update Travis to node 12, because why not?

MARBLE-974 fix build for Travis

---

@ndlib/gatsby-theme-marble/src/utils/__tests__/test.mapStandardJson.js
@ndlib/gatsby-theme-marble/src/utils/mapStandardJson/index.js
scripts/gatsby-source-iiif/indexSearch.js

Added mapping for the campus location. 
Fixed mappings for copyright fields that are showing up when they don't have a value.
Updated the text of general collection items in facet and in page to be correct.

fix missing node mappings

---

scripts/codebuild/install.sh
scripts/local.sh

The current version of the codebuild scripts expects the first argument to be the path to the values in parameter store. This works well enough if you're deploying locally, or if you have a pipeline custom-built for this behavior... But for a static-host-pipeline that is supposed to be generic, it felt a little too specific of an implementation to me.
This change uses an environment variable instead, but preserves the existing functionality by using `$1` as the default in case the environment variable is not already defined. The local script also defaults to "local" so you don't have to explicitly execute `local.sh local`, which is a bit redundant. :)

Change how path to parameter store is provided to codebuild scripts.

---

@ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserBody/PortfolioList/NewPortfolioButton/index.js
@ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserBody/PortfolioList/NewPortfolioButton/test.js
@ndlib/gatsby-theme-marble/src/components/Shared/Card/sx.js

* Due to previous refactor adding inline editing, `/edit` page for 
portofolios no longer exist.

MARBLE-1073 Fix Create new Portfolio Button

---

@ndlib/gatsby-theme-marble/src/components/Shared/ManifestDescription/index.js

I used the markdown display to catch that there are \n in the text we want to respect but that created an issue with the catalog convention [] for things that are uncertain. 
My fix is not great but these are other things i tried. 
disallowedTypes - disallowing the undocumented linkReference value just removes the text inside the [ ] 
setting a callback on linkReference.  the problem here is it ends up removing the [ ]  and because we don't know how complex props.children might be it is a little hard to put back.  also there realistically could be actual mark down here that we want.

update to have line breaks in the description

---

@ndlib/gatsby-theme-marble/gatsby-node.js
@ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ItemAlternateViews/AlternateImage/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ItemAlternateViews/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/index.js
@ndlib/gatsby-theme-marble/src/templates/marbleItem.js
@ndlib/gatsby-theme-marble/src/utils/__tests__/test.findImage.js
@ndlib/gatsby-theme-marble/src/utils/__tests__/test.mapImageMetadata.js
@ndlib/gatsby-theme-marble/src/utils/findImage.js
@ndlib/gatsby-theme-marble/src/utils/mapStandardJson/imageMetadata.js

* Link `marbleImage` to `marbleItem` in graphql.
* Use linked image instead of searching the hard way.
* Updated unit tests.

MARBLE-1135 Map images onto MarbleItem

---

@ndlib/gatsby-theme-marble/src/components/Internal/MetaDataList/MetaDataField/MetaDataMarkdownValue/index.js
@ndlib/gatsby-theme-marble/src/components/Internal/MetaDataList/MetaDataField/MetaDataMarkdownValue/test.js
@ndlib/gatsby-theme-marble/src/components/Internal/MetaDataList/MetaDataField/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchFilterBox/index.js
@ndlib/gatsby-theme-marble/src/utils/__tests__/test.punctuationStripper.js
@ndlib/gatsby-theme-marble/src/utils/mapStandardJson/index.js
@ndlib/gatsby-theme-marble/src/utils/mapStandardJson/makeMetadataArray.js
@ndlib/gatsby-theme-marble/src/utils/mapStandardJson/punctuationStripper.js
scripts/gatsby-source-iiif/indexSearch.js

A couple things here. 
Changed the display to not use markdown on fields unless we call for it. 
Added a search and an analyzer to search for things by id.  it removes punctuation from the search so it hopefully helps fuzzy matching of id searches. 
removed the punctuation from fields that are not being sent as filter keyword searches to ES. 
More to be done with the keyword properties including probably reorganizing somethings.

small steps on fixing the metadata.

---

scripts/codebuild/build.sh
scripts/codebuild/install.sh
scripts/gatsby-source-iiif/generate.sh

* We are going to do additional work next sprint to optimize the build. 
This simply disables the image harvesting steps which is suffient to 
return build times to previous levels and result in a working site with 
remote images.

Disable image harvesting

---

@ndlib/gatsby-theme-marble/src/components/Pages/MarbleItem/index.js
scripts/gatsby-source-iiif/indexSearch.js
scripts/gatsby-source-iiif/src/findThumbnail/test.js
scripts/gatsby-source-iiif/src/getKeywordsFromSubjects/index.js
scripts/gatsby-source-iiif/src/getKeywordsFromSubjects/test.js

The basic idea is we need to separate the 2 groups so that we can apply a different weights to searches found in each category.

Update indexing to separate themes

---

@ndlib/gatsby-theme-marble/src/components/Internal/ReturnToSearch/index.js
@ndlib/gatsby-theme-marble/src/components/Pages/MarbleItem/CollectionLayout/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/CardGroup/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ChildManifests/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/ManifestCardChildren/ChildField/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/ManifestCardChildren/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/ManifestCardChildren/test.js
@ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/TypeLabel/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/test.js
@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/HitResult/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/HitResult/test.js
@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/test.js
@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/searchSettings.js
@ndlib/gatsby-theme-marble/src/templates/marbleItem.js
@ndlib/gatsby-theme-marble/src/utils/findMetadata.js
site/.env.development
site/src/@ndlib/gatsby-theme-marble/components/Pages/IndexPage/index.js

* Refactor `ManifestCard` component to eliminate inefficient graphQl query.
* Modify uses of `ManifestCard` to reflect correct usage and pass in necessary props.
* Update unit tests

MARBLE-1188 Refactor ManifestCard to remove giant graphQl query

---

@ndlib/gatsby-theme-marble/src/components/Internal/ReturnToSearch/index.js
@ndlib/gatsby-theme-marble/src/components/Pages/MiradorViewer/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/HorizontalRule/index.js
README.md
site/content/README.md
site/src/@ndlib/gatsby-theme-marble/components/Pages/ExhibitsPage/index.js
site/src/@ndlib/gatsby-theme-marble/components/Pages/MarbleItem/ItemLayout/TombstoneMetadata/TombstoneField/index.js
site/src/@ndlib/gatsby-theme-marble/components/Pages/MarbleItem/ItemLayout/TombstoneMetadata/index.js
site/src/@ndlib/gatsby-theme-marble/components/Pages/MarbleItem/ItemLayout/index.js

* This actually starts to address MARBLE-1259, MARBLE-1260, MARBLE-1261 and 
MARBLE-1262.
* Styling changes still need to happen for 1260 and 1261, but this gets 
the data in generally the right place.
* The majority of code changes are happening in the `/site` folder so we 
can retain a simpler Item layout page for 'site builder'
* This also fixes a couple of places where I found a typo trying to get the primary color.

MARBLE-1259 Move Item Page primary image to right

---

@ndlib/gatsby-theme-marble/src/components/Pages/MiradorViewer/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/BrowseBar/index.js
site/src/@ndlib/gatsby-theme-marble/components/Pages/IndexPage/index.js

These images are small enough that they get inlined with webpack. Having a progressively enhanced next gen format actually bloats the javascript.

Remove nextgen from inlined images

---

@ndlib/gatsby-theme-marble/src/components/Shared/SiblingItems/index.js
@ndlib/gatsby-theme-marble/src/templates/marbleItem.js
@ndlib/gatsby-theme-marble/src/utils/__tests__/test.getArrayNeighbors.js
@ndlib/gatsby-theme-marble/src/utils/getArrayNeighbors.js
site/src/@ndlib/gatsby-theme-marble/components/Pages/MarbleItem/ItemLayout/index.js

New component to show some of the sibling items for items that belong in a collection.
* Return the 3 items before and 3 items after the current item from the parent collection.
* Wraps around the ends of the array 
* Returns whole array of siblings minus the current item if more items are requested than are in the original array
* Component will not render if there are no siblings (includes items that do not have parent and items that are in collections of a single item)

MARBLE-1300 Sibling Item Display

---

@ndlib/gatsby-theme-marble/src/components/Shared/BrowseBar/sx.js

MARBLE-1283 Fix font size issue with "medium" browe bar

---

@ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/ManifestCardChildren/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/HitResult/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/searchSettings.js
scripts/gatsby-source-iiif/indexSearch.js

This fixes a couple of things.
1.  The collection name now appears in child records when they are displayed in search.  It has highlight hits as well. 
2.  Fixed the case where hits in all metadata did not always have a line break between them.  
3.  Ensure prune is called here too.

More small changes to search.

---

@ndlib/gatsby-theme-marble/src/components/Shared/SiblingItems/index.js
@ndlib/gatsby-theme-marble/src/templates/marbleItem.js
scripts/gatsby-source-iiif/src/findThumbnail/index.js

* Use the same findImage function as used other places to accomplish the same thing.
* Also update indexSearch's image check to make sure extension is valid.

Update Sibling Items to display pdf icon correctly

---

@ndlib/gatsby-theme-marble/src/components/Pages/MarbleItem/CollectionLayout/index.js
@ndlib/gatsby-theme-marble/src/utils/mapStandardJson/makeMetadataArray.js

Addition of Cover Image to collection pages. Due to the current change in data storage, this will need revisited. Currently just showing first child item in list as default image.

MARBLE-1338 Cover image needs shown on collection pages

---

scripts/gatsby-source-iiif/indexSearch.js
scripts/gatsby-source-iiif/setupEnv.js
scripts/reset-local-search-index.sh

This is for inquisitions because we don't want to search any of the parents.  
Added an env var that search keys off of.
ONLY_SEARCH_CHILDNODES='true' 
Added both ONLY_SEARCH_CHILDNODES and the skip metadata to the ssm env build script for CI.

updated search to allow you to only put children in the index

---

@ndlib/gatsby-theme-marble/src/assets/theme.js

Basically since the theme ui update we had to add theme.styles to the individual tags in the site. 
I can add this to the main class to catch all As in the main section without conflicting with the header and footer.

suggestion for fixing the link color issue.  

---

.gitignore
@ndlib/gatsby-source-appsync-marble-standard/gatsby-node.js
@ndlib/gatsby-source-appsync-marble-standard/src/getItems.js
@ndlib/gatsby-transformer-marbleitem/gatsby-node.js

* Add caching to `gatsby-source-appsync-marble-standard` plugin.
* Move node creation in `gatsby-transformer-marbleitem` so that `MarbleItem` nodes do not get garbage collected.

MARBLE-1472 Implement Cache for Source Plugin

---

@ndlib/gatsby-theme-marble/src/components/Shared/CalloutBox/index.js

MARBLE-1622 Apply word wrap formatting to Annotation section. If it is found that this is also needed elsewhere, the individual sx will need updated.

Apply word wrap to annotation

---

@ndlib/gatsby-theme-marble/src/assets/theme.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionModal/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ActionModal/sx.js

- Adds a "text" variant to button. Sometimes you want a "link" that opens a modal (or similar) instead of going to a different page. Rather than a hack that prevents an <a> tag from acting like a link that goes somewhere, it's better to just style a <button> to look like a link.
- Adds an optional footer to the ActionModal. This will always be visible at the bottom of the modal on screen, so you don't have to scroll down to find it if the modal contents are long. Helpful for keeping action buttons visible.
- Fixes an issue where the modal content was slightly overlapping the header, causing the spacing to be a little off and the scrollbar extending above the visible content box.

Add footer option to modals. Fix scrollbar in modal overlapping header.

---

.codeclimate.yml
@ndlib/gatsby-theme-marble/src/components/Shared/NDBrand/Breadcrumbs/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/NDBrand/Breadcrumbs/test.js

Update breadcrumbs to trim titles. 
Trys to trim at a few special chars.  
if it is still bigger than 60 trim at the last space within 60 chars.  
Updated style to only show the immediate parent crumb when the screens are small. 
Added tests and class declaration.

MARBLE-1707 breadcrumbs 

---

@ndlib/gatsby-theme-marble/src/components/Shared/Card/sx.js
@ndlib/gatsby-theme-marble/src/components/Shared/CardGroup/CardGroupToggle/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/CardGroup/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/index.js

1.  Made the wide view of the card revert to a narrow vertical card on the 2 smallest screens.  
2. Removed the ability to toggle a display between wide and vertical. 
3. expand the breakpoints for the grid view by one break point to attempt to have fewer crowded grid cards.

update card sizes so that they are narrow in small screens.

---

@ndlib/gatsby-theme-marble/src/components/Shared/MarbleItem/ItemLayout/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/MarbleItem/ItemLayout/sx.js
@ndlib/gatsby-theme-marble/src/components/Shared/MetaDataList/MetaDataField/sx.js

MARBLE 1746, 1747, 1752. Fixes to multiple metadata display issues

Fix multiple metadata display issues

---

@ndlib/gatsby-theme-marble/src/components/Shared/ShareButton/ShareModalContent/sx.js

MARBLE-1831, darken the grey color of the "Copied to clipboard" text.

Fix font color of clipboard notification

---

@ndlib/gatsby-theme-marble/src/assets/theme.js
@ndlib/gatsby-theme-marble/src/components/Shared/NDBrand/Header/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/NDBrand/Hero/FullBleed/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/NDBrand/Layout/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/NDBrand/Section/LeftNav/index.js

Using `vw` for layout is an issue when you assume that the page width should equal `100vw`. The browser may interpret view width to include the space where the vertical scrollbar is. This in turn causes the page contents to extend outside the boundaries of what is "visible", so you end up with a horizontal scrollbar for that little extra width. Most layout elements should be sized relative to their parent anyway. If you were to set a max-width on the parent container, you want it to fill the space within the bounds of the parent, not go beyond it because 90vw or 100vw happens to be wider.
This also fixes an issue with the attribution on the front page. It was previously anchored to the left which meant it could extend too far to the right and again create a scrollbar. This change anchors …

Don't display horizontal scrollbar when not necessary.

---

@ndlib/gatsby-theme-marble/src/store/actions/loginActions/index.js

If you don't have an account, the login reducer is supposed to receive NO_USER and allow you to create an account. In reality, it was throwing an exception because it could not evaluate `json.userName` since `json` can be undefined.

Fix error when account does not exist

---

@ndlib/gatsby-plugin-marble-elasticsearch/src/indexToElasticSearch.js
@ndlib/gatsby-source-appsync-marble/src/getItems/transform/formatSearchData/index.js
@ndlib/gatsby-source-appsync-marble/src/getItems/transform/index.js
@ndlib/gatsby-source-appsync-marble/src/getItems/transform/searchData/realDatesFromCatalogedDates/index.js
@ndlib/gatsby-source-appsync-marble/src/getItems/transform/searchData/realDatesFromCatalogedDates/test.js
@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchRefinementListFilter/index.js

The goal of this change is to fully support BC dates, but also categorize anything before a certain date under a single tag. This happens to be 1400 right now, but the value is configurable so that another site could conceivably use a different value which makes more sense based on the age of items in that collection.
This should resolve all issues where items from "1500 BCE" get lumped in the "1500-1599" range. There would be a separate tag for "1500 BCE-1401 BCE", if the cutoff date were configured to something before then. (Represented with a negative number; e.g. -2000) Additionally, this fixes issues where 0 was not being identified as a valid year, so ranges like "0-500" were only being given the 500-599 tag.
In practice, both of those situations fall before the cutoff date we'll …

Implement cutoff date for century tags.

---

@ndlib/gatsby-source-appsync-marble/src/getItems/transform/formatSearchData/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchRefinementListFilter/index.js

Adds the ability to override the label in the facet list. Useful if you want to index a value (particularly booleans) but display something different in the UI for usability purposes.

MARBLE-1906 allow faceting on whether an item has images or not

---

@ndlib/gatsby-theme-marble/src/components/Shared/MarbleItem/RelatedItemsFromSearch/index.js

The default for elasticsearch looks for a 30% match. This is going to vary wildly depending on the item metadata of the item you are coming from and searching for, so it won't do a great job if the metadata is fairly limited. Changing this to 1 should allow the query to more consistently return anything remotely related. (It will still sort the results by score so you get the most relevant results first.)
I don't have an explanation for why the results for an individual item might change, without a change in the metadata. But at least this should usually give _something_. We can refine the number if POs find the items aren't similar enough and it should be stricter.

MARBLE-1909 Increase related items search results

---

@ndlib/gatsby-theme-marble/src/components/Shared/ActionModal/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ShareButton/ShareModalContent/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ShareButton/ShareModalContent/sx.js
@ndlib/gatsby-theme-marble/src/components/Shared/ShareButton/ShareModalContent/test.js
@ndlib/gatsby-theme-marble/src/components/Shared/ShareButton/index.js

I added a "short" prop to the modal which behaves similarly to "fullscreen" by altering styles. The short prop sets the height to auto instead of forcing the modal to expand based on the window height, leaving a bunch of whitespace below. It's not super elegant, but is more reusable than passing a custom style.

MARBLE-1868 Update share modal styling

---

@ndlib/gatsby-theme-marble/src/components/Shared/DisplayCard/sx.js
@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/HitResult/index.js

* Hide some extra information on search in grid view
* Correctly truncate title to 2 lines and body text to 4 (grid) or 8 (list) lines. Uses ellipsis instead of more because this is more correct for accessibility.
* Minor adjustments to default height of cards
* Change portfolio page to only have a max of 2 cards wide (let's look at this and decide if change should be carried over to search).
* Forces list view cards to behave like grid cards (image on top) for narrow widths.

MARBLE-1925, 1927, 1928 Card adjustments

---

@ndlib/gatsby-theme-marble/src/utils/api.js

Saving unescaped newlines and other special characters can cause saves to the portfolio tool to fail. This does a encode and decodes certain fields that may be problematic.
**See also:**
https://github.com/ndlib/marble-web/pull/130
**This should get some QA on test before approval to production.**

MARBLE-2015 Encode/Decode text going to AppSync

---

@ndlib/gatsby-source-appsync-marble-inquisition/src/getItems/transform/index.js

* Use INQ number (`uniqueIdentifer`) instead of `id` for slug.
* Fallback to `id` when there is no `uniqueIdentifer`

MARBLE-2036 INQ numbers in slug

---

@ndlib/gatsby-source-appsync-marble-inquisition/src/getItems/transform/formatSearchData/index.js
@ndlib/gatsby-source-appsync-marble-inquisition/src/getItems/transform/index.js

* Use `uniqueIdentifier` if it exists instead of `id` for the creation of slugs
* Fallback to `id` for items without a `uniqueIdentifer`
* Update the elasticsearch `url` field to match the generated `slug`
**Example:**
https://inquisition.library.nd.edu/item/001588193 becomes https://inquisition.library.nd.edu/item/INQ-64

MARBLE-2036 Use INQ numbers in urls for Inquisition

---

@ndlib/gatsby-source-appsync-marble-inquisition/gatsby-node.js
@ndlib/gatsby-source-appsync-marble-inquisition/src/getItems/transform/index.js
@ndlib/gatsby-source-appsync-marble/gatsby-node.js
@ndlib/gatsby-source-appsync-marble/src/getItems/transform/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/AdditionalDescription/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/AdditionalDescription/test.js
@ndlib/gatsby-theme-marble/src/components/Shared/MarbleItem/ItemLayout/TombstoneMetadata/index.js

* Assign `additionalNotes` to `addtionalDescription` field in `marbleItem`
* Display `addtionalDescription` below the regular `description` field
See also:
https://github.com/ndlib/marble-web/pull/143
https://github.com/ndlib/inquisition/pull/89

MARBLE-2064 Add additional notes field from Redbox

---

@ndlib/gatsby-source-appsync-marble-inquisition/gatsby-node.js
@ndlib/gatsby-source-appsync-marble-inquisition/src/getItems/queryItem.js
@ndlib/gatsby-source-appsync-marble-inquisition/src/getItems/transform/getIiif/index.js
@ndlib/gatsby-source-appsync-marble-inquisition/src/getItems/transform/index.js
@ndlib/gatsby-source-appsync-marble-inquisition/src/getItems/transform/searchData/getThumbnail/index.js
@ndlib/gatsby-source-appsync-marble/gatsby-node.js
@ndlib/gatsby-source-appsync-marble/src/getItems/queryItem.js
@ndlib/gatsby-source-appsync-marble/src/getItems/transform/getIiif/index.js
@ndlib/gatsby-source-appsync-marble/src/getItems/transform/index.js
@ndlib/gatsby-source-appsync-marble/src/getItems/transform/searchData/getThumbnail/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ItemAlternateViews/AlternateImage/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ItemAlternateViews/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ItemAlternateViews/test.js
@ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/test.js
@ndlib/gatsby-theme-marble/src/utils/findImage.js

* Add default image to sourcing graphQl queries for marble and inquisition
* Use the default image as the thumbnail for search results
* Use the default image as the main image on the item page.
* Adjust additional/alternative image after main image to start with the first image in the sequence since the main image is no longer guaranteed to be the first image of the sequence.
* Update affected unit tests
**See also:**
* https://github.com/ndlib/marble-web/pull/144
* https://github.com/ndlib/inquisition/pull/90

MARBLE-2061 Use Default Image

---

@ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/index.js
@ndlib/gatsby-theme-marble/src/utils/findImage.js

Quick fix for missing defaultImage when image children exist.
* Fall back to looking through child images if they exist when defaultImage is null.

Fix some missing images when data is missing

---

@ndlib/gatsby-source-appsync-marble-inquisition/src/getItems/transform/searchData/getThumbnail/index.js
@ndlib/gatsby-source-appsync-marble/src/getItems/transform/searchData/getThumbnail/index.js

* `defaultImage` is returning a width and height for some items even when there is no mediaServer or mediaResourceId, so we need to expand the null check.
* Expand null check to specifically check for the two fields we use to build the image path.

Fix image on search results for items with missing defaultImage

---

@ndlib/gatsby-theme-marble/src/components/Shared/DisplayCard/CardShell/LinkOrWrapper/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/DisplayCard/CardShell/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/DisplayCard/MarbleItemCard/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/DisplayCard/index.js
@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/HitResult/index.js

When `Card` was refactored into `DisplayCard` and it's derivatives, state was not being passed down. This reenables this functionality.

MARBLE-1975 Fix ReturnToSearch  regression

---

@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchFilterBox/index.js
yarn.lock

This helps identifiers with hyphens like "INQ-123" work in search.

MARBLE-2099 Make identifier search work closer to expected

---

@ndlib/gatsby-source-appsync-marble/src/getItems/queryItem.js

New hard limit of 10,000 images per item (increased from default 1000).

MARBLE-2132 Fix item images from getting truncated at 1000
