src/components/Layout/index.js, src/components/Layout/style.module.css, src/components/ManifestViews/Collection/CollectionAside/index.js, src/components/ManifestViews/Collection/CollectionPreMain/index.js, src/components/ManifestViews/Collection/index.js, src/components/ManifestViews/Item/ItemAside/ImageSection/index.js, src/components/ManifestViews/Item/ItemAside/index.js, src/components/ManifestViews/Item/ItemPreMain/index.js, src/components/ManifestViews/Item/index.js, src/components/ManifestViews/Item/style.module.css, src/components/Shared/ActionButtonGroup/ActionButton/index.js, src/components/Shared/ActionButtonGroup/ActionButton/style.module.css, src/components/Shared/ActionButtonGroup/index.js, src/components/Shared/ActionButtonGroup/style.module.css, src/components/Shared/Breadcrumb/index.js, src/components/Shared/Breadcrumb/style.module.css, src/components/Shared/DisplayViewToggle/index.js, src/components/Shared/MetaDataList/index.js, src/templates/browse.js, src/templates/iiif-collection.js, src/templates/iiif-manifest.js
Porting over more Collection and Item page components.
Adjustments to Layout.
=> MEL-229 MEL-230 Item and Collection Layouts

gatsby-node.js, plugins/gatsby-source-iiif/gatsby-node.js, src/templates/browse.js
1.  Added slugs to categories.
2. Added subCategores as a foreign key 
3. Added parentCategory as a foreign key 
4. Added topLevelParentCateogry  as a foreign key (the child of root this category is under)
=> Added foreign key references for the category tree structure.

gatsby-browser.js, gatsby-config.js, gatsby-ssr.js, package.json, src/components/APIViews/Search/SearchDisplay/PageNum/PaginationButton/index.js, src/components/APIViews/Search/SearchDisplay/PageNum/index.js, src/components/APIViews/Search/SearchDisplay/PageNum/style.module.css, src/components/APIViews/Search/SearchDisplay/PerPage/index.js, src/components/APIViews/Search/SearchDisplay/PerPage/style.module.css, src/components/APIViews/Search/SearchDisplay/Results/Result/index.js, src/components/APIViews/Search/SearchDisplay/Results/index.js, src/components/APIViews/Search/SearchDisplay/index.js, src/components/APIViews/Search/index.js, src/components/ManifestViews/Item/ItemAside/ImageSection/index.js, src/components/ManifestViews/UniversalViewer/UniversalViewerLayout/index.js, src/components/Shared/ActionButtonGroup/index.js, src/components/Shared/Loading/index.js, src/components/Shared/Loading/style.module.css, src/components/Shared/Thumbnail/index.js, src/pages/search.js, src/store/ReduxWrapper/index.js, src/store/actions/searchActions/index.js, src/store/configureStore.js, src/store/reducers/index.js, src/store/reducers/searchReducer/index.js, src/templates/iiif-collection.js, src/templates/iiif-manifest.js, src/utils/fetchJSON.js, yarn.lock
* Add in redux and react-redux
* Porting over search reducer
=> MEL-328 Hydration example

src/assets/images/noImage.svg, src/components/ManifestViews/Browse/index.js, src/components/ManifestViews/Collection/CollectionPreMain/index.js, src/components/ManifestViews/Item/ItemPreMain/index.js, src/components/Shared/Breadcrumb/index.js, src/components/Shared/Card/index.js, src/templates/browse.js
* Basic implementation of browse view based on data we have now
* Add simple breadcrumb to browse
* Add noImage image to cards
=> MEL-360 Browse View

src/components/ManifestViews/Collection/CollectionPreMain/index.js, src/components/ManifestViews/Collection/index.js, src/components/ManifestViews/Item/ItemAside/ImageSection/ItemAlternateViews/AlternateImage/AlternateOverlay/index.js, src/components/ManifestViews/Item/ItemAside/ImageSection/ItemAlternateViews/AlternateImage/index.js, src/components/ManifestViews/Item/ItemAside/ImageSection/ItemAlternateViews/index.js, src/components/ManifestViews/Item/ItemAside/ImageSection/index.js, src/components/ManifestViews/UniversalViewer/UniversalViewerLayout/index.js, src/components/Shared/Card/index.js, src/components/Shared/Image/index.js, src/templates/iiif-collection.js, src/utils/getImageService.js
* Create an Image component
* Use Image component in: Card, all  IIIF images on Item and Collection pages
* Fix UniversalViewer to accept `cv` for correct links from AlternateImage
=> MEL-363, MEL-364 Image Work

src/components/Layout/ContentWrapper/style.module.css, src/components/Layout/PageContent/style.module.css, src/components/ManifestViews/Item/ItemAside/ImageSection/ItemAlternateViews/AlternateImage/style.module.css, src/components/ManifestViews/Item/style.module.css, src/components/ManifestViews/UniversalViewer/UniversalViewerLayout/index.js, src/components/ManifestViews/UniversalViewer/UniversalViewerLayout/style.module.css, src/components/ManifestViews/UniversalViewer/UniversalViewerLayout/test.js, src/components/ManifestViews/UniversalViewer/index.js
* Add mobile breakpoints
* MEL-402 clean up css
* Bonus: Make UV full screen and add unit test for it.
=> MEL-401 Add mobile breakpoints

src/assets/icons/svg/baseline-menu-24px-white.svg, src/assets/icons/svg/baseline-menu-24px.svg, src/assets/icons/svg/baseline-person-24px-white.svg, src/assets/icons/svg/baseline-person-24px.svg, src/components/Layout/ContentWrapper/style.module.css, src/components/Layout/PageContent/style.module.css, src/components/Layout/PageWrapper/NavigationHeader/HamburgerButton/index.js, src/components/Layout/PageWrapper/NavigationHeader/HamburgerButton/test.js, src/components/Layout/PageWrapper/NavigationHeader/LoginButton/index.js, src/components/Layout/PageWrapper/NavigationHeader/LoginButton/style.module.css, src/components/Layout/PageWrapper/NavigationHeader/LoginButton/test.js, src/components/Layout/PageWrapper/NavigationHeader/SiteLogo/index.js, src/components/Layout/PageWrapper/NavigationHeader/SiteLogo/style.module.css, src/components/Layout/PageWrapper/NavigationHeader/SiteLogo/test.js, src/components/Layout/PageWrapper/NavigationHeader/index.js, src/components/Layout/PageWrapper/NavigationHeader/style.module.css, src/components/Layout/PageWrapper/NavigationHeader/test.js, src/components/Layout/PageWrapper/SkipToMain/index.js, src/components/Layout/PageWrapper/SkipToMain/test.js, src/components/Layout/PageWrapper/index.js, src/components/Layout/PageWrapper/test.js, src/components/Layout/index.js, src/components/ManifestViews/Collection/index.js, src/components/ManifestViews/Item/ItemAside/ImageSection/ItemAlternateViews/AlternateImage/style.module.css
* Fix layout for main navigation
* Make it mobile responsive 🍔
* Fun stuff with the login button
* Unit tests
=> MEL-399 Main navigation improvements

src/components/ManifestViews/Collection/index.js, src/components/ManifestViews/Collection/test.js, src/components/Shared/Card/index.js, src/components/Shared/Card/style.css, src/components/Shared/DisplayViewToggle/ToggleButton/test.js, src/components/Shared/DisplayViewToggle/index.js, src/components/Shared/DisplayViewToggle/test.js, src/store/actions/displayActions/index.js, src/store/actions/displayActions/test.js, src/store/reducers/displayReducer/index.js, src/store/reducers/index.js, src/templates/__tests__/test.iiif-collection.js, src/templates/iiif-collection.js
* Move grid/list toggle to redux store
* Create css style for `.list` Cards
* Get Collection grid/list view working
* Unit tests
**TODO:** 
* Get Search grid/list toggle working after Search page refactor.
=> MEL-362 Grid/List toggle

package.json, yarn.lock
Fixes hot reloading issue:
https://github.com/gatsbyjs/gatsby/pull/13713
=> Gatsby 2.5.2 update

package.json, src/components/Layout/index.js, src/components/Shared/ConstructionBanner/index.js, src/components/Shared/ConstructionBanner/style.module.css, src/components/Shared/ConstructionBanner/test.js
* Duplicate style of construction banner on SPA.
* Add in current version pulled from package.json
=> Construction banner

src/components/Schema/basicschema1.json, src/components/Schema/basicschema2.json, src/components/Schema/basicschema3.json, src/components/Schema/rendering.json, src/pages/__tests__/test.metatest.js, src/pages/metatest.js
Bringing MetaTest over to Gatsby build
=> Metatest port

package.json, src/pages/search-new.js, yarn.lock
* Disable infinite scroll on search
* Increase results to 48
=> MEL-432 Disable infinte scroll on search

src/assets/icons/svg/baseline-open_in_new-24px-white.svg, src/assets/icons/svg/baseline-open_in_new-24px.svg, src/components/Shared/Card/ExteralLinkIcon/index.js, src/components/Shared/Card/ExteralLinkIcon/style.module.css, src/components/Shared/Card/ExteralLinkIcon/test.js, src/components/Shared/Card/index.js, src/components/Shared/Card/test.js, src/components/Shared/Link/index.js
=> MEL-421 Add external link icon to cards that open in a different site.

package.json, src/components/ManifestViews/Browse/index.js, src/components/ManifestViews/Collection/CollectionPreMain/index.js, src/components/ManifestViews/Collection/index.js, src/components/ManifestViews/Item/ItemAside/ImageSection/index.js, src/components/Shared/Card/index.js, src/components/Shared/Image/index.js, src/templates/browse.js, src/templates/iiif-manifest.js, src/utils/__tests__/test.getImageService.js, src/utils/getImageService.js, yarn.lock
* Image component will attempt to build a `srcset` if a `service` prop is passed into it. It will evaluate the `size` prop to determine if it has pixel values and multiply those by the appropriate amount.
* `srcset` uses x descriptors
=> MEL-442 Add srcset to Image component

content/manifests.json, gatsby-config.js, package.json, yarn.lock
https://www.gatsbyjs.org/packages/gatsby-plugin-sitemap/
=> Add sitemap.xml generation

src/components/MicroComp/datemicro.js, src/components/MicroComp/linkmicro.js, src/components/Schema/basicschema2.json, src/components/Schema/basicschema3.json, src/components/Schema/rendering.json, src/pages/__tests__/test.date.js, src/pages/__tests__/test.default.js, src/pages/__tests__/test.title.js, src/pages/metatest.js
Added license URL. Corrected minor differences to match CreativeWork format.
=> MEL-428 Adding date to metadata building.

content/markdown/test/savedSearch.md, src/components/Pages/Markdown/availableComponents.js, src/components/Shared/SavedSearch/index.js
A little quick and dirty. I intend to cleanup and test after / along side the research task looking at alternate search component libraries.
=> MEL-478 Saved Search Component

.travis.yml, plugins/gatsby-source-iiif/README.md, plugins/gatsby-source-iiif/generateMD.js, plugins/gatsby-source-iiif/getManifests.js, plugins/gatsby-source-iiif/src/fetchManifests/fixIiifJson/index.js, plugins/gatsby-source-iiif/src/fetchManifests/index.js
Note this means to get the manifests and make markdown for them you have to do both
node getManifests.js
node generateMD.js
=> Reorganize the plugin to have 2 scripts

src/components/Internal/MetaDataList/MetaDataField/MetaDataLabel/index.js, src/components/Internal/MetaDataList/MetaDataField/MetaDataLabel/test.js, src/components/Internal/MetaDataList/MetaDataField/MetaDataValue/index.js, src/components/Internal/MetaDataList/MetaDataField/MetaDataValue/test.js, src/components/Internal/MetaDataList/MetaDataField/index.js, src/components/Internal/MetaDataList/MetaDataField/test.js, src/components/Internal/MetaDataList/index.js, src/components/Internal/MetaDataList/test.js, src/components/Pages/MiradorViewer/index.js, src/components/Shared/ManifestCard/index.js, src/components/Shared/ManifestDescription/index.js, src/components/Shared/ManifestDescription/test.js, src/components/Shared/ManifestMetaData/index.js, src/utils/__tests__/test.getLanguage.js, src/utils/getLanguage.js
=> MEL-496 Use language configuration

@hesburgh-wse/gatsby-theme-marble/src/components/Shared/Card/style.css, site/content/markdown/home.md
* Move text above search bar
* Fix layout bug with Cards viewed as list.
=> MEL-517 Update Home page with some real things.

.travis.yml
=> Fix unit test coverage reporting

scripts/gatsby-source-iiif/generateMDCategories.js, scripts/gatsby-source-iiif/indexSearch.js, site/content/categories.json
This should make all the manifests appear in the correct tags.
=> fix to use the old tagging.

@hesburgh-wse/gatsby-theme-marble/gatsby-config.js, @hesburgh-wse/gatsby-theme-marble/gatsby-node.js, @hesburgh-wse/gatsby-theme-marble/package.json, @hesburgh-wse/gatsby-theme-marble/src/components/Experimental/User/UserCollection/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/Experimental/User/UserLanding/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/Experimental/User/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/Layout/PrivateRoute/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/Layout/PrivateRoute/test.js, @hesburgh-wse/gatsby-theme-marble/src/components/Shared/LoginArea/index.js, @hesburgh-wse/gatsby-theme-marble/src/pages/user.js, fake-api/db.json, fake-api/index.js, fake-api/package.json, package.json, site-collection-tools/.gitignore, site-collection-tools/content/configuration.js, site-collection-tools/content/markdown/404.md, site-collection-tools/content/markdown/home.md, site-collection-tools/content/markdown/login.md, site-collection-tools/gatsby-config.js, site-collection-tools/package.json, yarn.lock
* **MEL-531** Determine framework
* Continue with Gatsby. Splitting into separate project seems like overkill at this point.
* **MEL-528** & **MEL-529** Create Repo and Base Project
* Created `site-collection-tools` folder for testing login & user page stuff without interfering with main `site` content.
* Created `fake-api` folder to serve a fake api end point (will be used for data testing in future PR).
* Run: `yarn workspace fake-api develop`
* Endpoint: `http://localhost:9000/users/username/`
* Edit `fake-api/db.json` to modify server response.
* **MEL-530** Add some of the specified routes in the collection tool
* Added following routes:
* `/user/:username`
* `/user/:username/:collectionId`
* Additional changes:
* After logging in the user is redirected to `/user` instead of `/`
* If …
=> MEL-528, MEL-529, MEL-530, MEL-531

@hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/Compliation/CompilationUnavailable/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/Compliation/CompilationUnavailable/style.module.css, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/Compliation/ItemList/Item/ViewerButtons/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/Compliation/ItemList/Item/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/Compliation/ItemList/Ownership/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/Compliation/ItemList/Ownership/style.module.css, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/Compliation/ItemList/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/Compliation/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/Compliation/style.module.css, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/User/LoginOrRedirect/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/User/NoUser/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/User/UserEdit/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/User/UserFollowing/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/User/UserIndex/CompilationList/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/User/UserIndex/CompilationList/style.module.css, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/User/UserIndex/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/User/UserLayout/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/Internal/MaterialButton/style.module.css, @hesburgh-wse/gatsby-theme-marble/src/components/Internal/VisibilityLabel/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/Internal/VisibilityLabel/style.module.css, @hesburgh-wse/gatsby-theme-marble/src/components/Shared/LoginArea/style.module.css, @hesburgh-wse/gatsby-theme-marble/src/utils/appUtils.js
* Adding layout for page `compilation/:compilationId`
* Adding is some visibility levels: `private`, `public`, `shared`
* Do some basic showing and hiding based on this visibility and logged in state
* Handle user not found
* Handle compilation not found
* move mock data to external file `utils/appUtils.js`
=> MEL-551 Users need individual pages for their collections

@hesburgh-wse/gatsby-theme-marble/src/assets/theme.js, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/Compliation/ItemList/Ownership/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/Compliation/ItemList/Ownership/style.module.css, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/Compliation/ItemList/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/App/Pages/Compliation/style.module.css, @hesburgh-wse/gatsby-theme-marble/src/components/Internal/Attribution/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/Internal/CalloutBox/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/Internal/CalloutBox/style.module.css, @hesburgh-wse/gatsby-theme-marble/src/components/Internal/UserAnnotation/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/Internal/UserCartouche/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/Internal/UserCartouche/style.module.css, @hesburgh-wse/gatsby-theme-marble/src/components/Layout/PageContent/index.js, @hesburgh-wse/gatsby-theme-marble/src/components/Layout/PageContent/test.js, @hesburgh-wse/gatsby-theme-marble/src/components/Layout/index.js, @hesburgh-wse/gatsby-theme-marble/src/utils/appUtils.js
* Add "annotations" to item and collection pages from compilation pages
=> Some additional changes to Compilation pages

@hesburgh-wse/gatsby-theme-marble/src/components/Pages/MiradorViewer/index.js
* Research how to add a zoom in and out button on mirador
* Also fix pagination bug
=> MEL-543 Zoom Controls on Mirador

@ndlib/gatsby-theme-marble/gatsby-node.js, @ndlib/gatsby-theme-marble/src/components/Internal/Seo/index.js, @ndlib/gatsby-theme-marble/src/components/Internal/Seo/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/ChildManifests/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/test.js, site/content/markdown/home.md
* Change the links on the homepage to be the right browse pages.
* Make sure the list page is the default for the search.
* Fix `summary` field in a few places
=> MEL-565 and MEL-566

@ndlib/gatsby-theme-marble/gatsby-node.js, @ndlib/gatsby-theme-marble/package.json, @ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserEdit/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserLayout/index.js, @ndlib/gatsby-theme-marble/src/components/Layout/AuthWrapper/index.js, @ndlib/gatsby-theme-marble/src/components/Layout/PrivateRoute/index.js, @ndlib/gatsby-theme-marble/src/components/Layout/PrivateRoute/test.js, @ndlib/gatsby-theme-marble/src/components/Layout/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/LoginArea/LogOut/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/LoginArea/OktaLogin/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/LoginArea/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/LoginArea/test.js, @ndlib/gatsby-theme-marble/src/store/actions/loginActions/index.js, @ndlib/gatsby-theme-marble/src/store/reducers/loginReducer/index.js, site/content/configuration.js, yarn.lock
* Okta login should work for `dwolfe2` and `jhartzle`.
**TODO**: Clean up & start unit testing.
=> MEL-555 Get Okta to work

@ndlib/gatsby-theme-marble/src/assets/theme.js, @ndlib/gatsby-theme-marble/src/components/Layout/ContentWrapper/style.module.css, @ndlib/gatsby-theme-marble/src/components/Shared/HeroBox/index.js
* fixes layout on large displays
* fixes overflow
=> Quick CSS fix for HeroBox

@ndlib/gatsby-theme-marble/gatsby-node.js, @ndlib/gatsby-theme-marble/src/components/Pages/Markdown/availableComponents.js, @ndlib/gatsby-theme-marble/src/components/Shared/HeroBox/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/PartiallyDigitized/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/PartiallyDigitized/test.js, @ndlib/gatsby-theme-marble/src/templates/markdownTemplate.js
Basic component that looks at the `partiallyDigitized` field and renders a notice if it exists. In the future this may be updated to include additional information such as who to contact for more information  or where to find a more authoratative source.
=> MARBLE-603: Display info when dataset in not complete

.eslintrc, @ndlib/gatsby-theme-marble/gatsby-node.js, @ndlib/gatsby-theme-marble/src/components/Layout/AuthWrapper/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/LoginArea/OktaLogin/index.js, @ndlib/gatsby-theme-marble/src/store/actions/loginActions/index.js, @ndlib/gatsby-theme-marble/src/store/actions/loginActions/test.js, site/content/configuration.js
* Switch to using real Okta account
* Add correct issuer
=> MARBLE-643 Switch site to use ND Okta Credentials

@ndlib/gatsby-theme-marble/src/components/App/Pages/Portfolio/PortfolioBody/PortfolioView/PortfolioDisplay/Item/ViewerButtons/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/Portfolio/PortfolioBody/PortfolioView/PortfolioDisplay/Item/index.js
* Make the "View in Mirador" button work.
* Remove UV button.
=> Make view Item in Mirador button work

@ndlib/gatsby-theme-marble/gatsby-node.js, @ndlib/gatsby-theme-marble/src/pages/all.js
a simple page to see a list of all the items. 
Needs more work since they are not grouped.
=> add all page.

@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchFilterBox/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchSortingSelector/index.js, scripts/gatsby-source-iiif/indexSearch.js
1.  Changed the search to work of a custom query to prioritize phrase matching. 
2.  added hightlight text into the search results. 
3.  added relavance to the search results so you see what it thinks is actually most relavant and not alphabetical. 
4. augmented allMetadata with more data for now.  but really the search needs to be expanded to be smarter.
=> some changes to the search.

@ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/test.js, scripts/gatsby-source-iiif/indexSearch.js, site/content/configuration.js
Changed the manifest card to take children that get displayed in the description section of the card.
=> add hit display to the search results.

@ndlib/gatsby-theme-marble/gatsby-node.js
Change order of Format and Keyword
=> MARBLE-72 pt 1: Change order of Format and Keyword

@ndlib/gatsby-theme-marble/package.json, @ndlib/gatsby-theme-marble/src/components/Internal/UserAnnotation/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchRefinementListFilter/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchRefinementListFilter/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/index.js, yarn.lock
* Update `searchkit`
* Add default value for `size` to `SearchRefinementListFilter`
* Fix `null` check for `hit.highlight`
* Prevent `UserAnnotation` from being called on non-items pages.
=> MARBLE-743 Fix Search

@ndlib/gatsby-theme-marble/src/components/Layout/PageWrapper/NavigationHeader/LoginButton/index.js, @ndlib/gatsby-theme-marble/src/components/Layout/PageWrapper/NavigationHeader/LoginButton/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/LoginArea/OktaLogin/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/LoginArea/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/LoginArea/style.module.css, @ndlib/gatsby-theme-marble/src/components/Shared/LoginArea/test.js
* "Log in" - action, not "Login" - noun corrections
* Add text to Login page.
* Remove Facebook and Google placeholders
=> MARBLE-745 Clean up Login page.

scripts/gatsby-source-iiif/indexSearch.js
Quick fix to get themes back on the site. 
I am working on a better solution with tests.  Just need to see them for Abby to test.
=> quick fix to get theme back.

@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkButton/index.js
* Change "+" and "-" to styled "Add" and "Remove"
=> MARBLE-750 CHange text in dropdown

@ndlib/gatsby-theme-marble/src/components/App/Pages/Portfolio/PortfolioBody/PortfolioEdit/EditItems/EditItem/EditItemForm/EditItemFormContent/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/Portfolio/PortfolioBody/PortfolioEdit/EditItems/EditItem/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/Portfolio/PortfolioBody/PortfolioEdit/EditItems/EditItem/sx.js
* Remove `title` and other fields that were previously disabled from 
editing
* Add "pencil" edit icon. Styling is placeholder.
=> MARBLE-752 Cleanup Item Edit in Portfolios

scripts/gatsby-source-iiif/indexSearch.js, scripts/gatsby-source-iiif/package.json, scripts/gatsby-source-iiif/src/getCenturyTagsFromDate/index.js, scripts/gatsby-source-iiif/src/getCenturyTagsFromDate/test.js, scripts/gatsby-source-iiif/src/getKeywordsFromSubjects/index.js, scripts/gatsby-source-iiif/src/getKeywordsFromSubjects/test.js, scripts/gatsby-source-iiif/yarn.lock
updated the way indexing was working to have tests and to have some library extractions for both readability and test ability.
=> add tests and extracted functions to indexing

scripts/codebuild/install.sh, scripts/gatsby-source-iiif/indexSearch.js, site/.env.development, site/.gitignore, site/content/configuration.js
* Change `/site/content/configuration.js` to correctly use environment 
variables
* cp `/.env` to `/site/.env.production` during install
=> Gatsby Environment Variables

@ndlib/gatsby-theme-marble/gatsby-node.js, @ndlib/gatsby-theme-marble/src/assets/css/global.css, @ndlib/gatsby-theme-marble/src/components/Internal/DisplayViewToggle/DisplayViewToggleInternal/index.js, @ndlib/gatsby-theme-marble/src/components/Internal/DisplayViewToggle/DisplayViewToggleInternal/sx.js, @ndlib/gatsby-theme-marble/src/components/Internal/DisplayViewToggle/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/HeroBox/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchSortingSelector/index.js, site/src/@ndlib/gatsby-theme-marble/components/Shared/SearchTools/SearchFilterBox/index.js
* Remove space and place creators on separate lines
* Update unit test
* Restore default display of creator and dates on search results
* css cleanup on searchbox
=> MARBLE-777 Remove space between creators on search results

@ndlib/gatsby-theme-marble/package.json, @ndlib/gatsby-theme-marble/src/components/Shared/Image/index.js, @ndlib/gatsby-theme-marble/yarn.lock
* This was tracked down to the way we were doing progressive image loading.
* Removed `react-waypoint` module.
=> MARBLE-823 Sorting results doesn't update image order

@ndlib/gatsby-theme-marble/package.json, @ndlib/gatsby-theme-marble/src/assets/css/global.css, @ndlib/gatsby-theme-marble/src/components/Internal/ActionModal/index.js, @ndlib/gatsby-theme-marble/src/components/Internal/ActionModal/sx.js, @ndlib/gatsby-theme-marble/src/components/Internal/ActionModal/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadModalContent/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/ShareModalContent/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/ShareModalContent/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/ShareModalContent/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/test.js, yarn.lock
* Add `react-modal` library and create base styles for minimal and 
fullscreen modals
* Add modal popup when "Share" button pressed.
* Modal has url of current page that can be copied to clipboard but 
clicking the copy button or the url. A message appears below the url to 
alert the user that the url has been copied to their clipboard.
*  Create stub file for download modal.
=> MARBLE-816: Share button does something

@ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserBasePath/UserBasePathContent/CreateAccount/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserBody/UserEdit/index.js
* Fix the url for update user
* Fix default name not being populated
=> MARBLE-808 Partial fix for 401s

scripts/gatsby-source-iiif/indexSearch.js, scripts/gatsby-source-iiif/src/getCreators/index.js, scripts/gatsby-source-iiif/src/getCreators/test.js
We changed the metadata field from creator -> creators
=> fix missing creators in search

@ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserBasePath/UserBasePathContent/CreateAccount/WelcomeMessage/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserBasePath/UserBasePathContent/CreateAccount/index.js, site/src/@ndlib/gatsby-theme-marble/components/App/Pages/User/UserBasePath/UserBasePathContent/CreateAccount/WelcomeMessage/index.js
* Move welcome text to small component that can be overwritten in the 
shadow components
* Include text from PO in shadow component.
=> MARBLE-784 Implement PO-requested edits on first time new user log-in page

@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/Pager/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/Pager/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/index.js, site/content/menus.js
* Add default `searchkit` `Pagination` component.
* Wrapper in some sx style.
=> MARBLE-807 Users need a way to page through search results.

scripts/gatsby-source-iiif/indexSearch.js, site/content/search/.gitignore
Changed the bulk indexer both force: true and then to print individual errors.
=> update indexing to try and test issues with elastic search

@ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserBody/PortfolioList/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/BookmarkButton/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchBox/SearchButton/test.js
* Update portfolios that have no image to use image from first item with an 
image when that item is added.
* Fix unrelated broken unit test
=> MARBLE-853 Update Portfolio cover images

@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/test.js
* IIIF link and better information exist in download modal.
=> MARBLE-862 Remove IIIF icon from object record page

@ndlib/gatsby-theme-marble/gatsby-node.js, @ndlib/gatsby-theme-marble/src/assets/i18n/json/common.default.en.json, @ndlib/gatsby-theme-marble/src/assets/i18n/json/text.default.en.json, @ndlib/gatsby-theme-marble/src/components/App/Pages/User/LogOut/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/User/NoUser/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserBody/PortfolioList/NewPortfolioButton/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserLayout/EditUserButton/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserLayout/EditUserButton/test.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserLayout/PromptLogin/index.js, @ndlib/gatsby-theme-marble/src/components/Internal/VisibilityLabel/index.js, @ndlib/gatsby-theme-marble/src/components/Layout/PageWrapper/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/LoginArea/LogOut/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/LoginArea/OktaLogin/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/LoginArea/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchBox/SearchField/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchBox/SearchField/test.js, @ndlib/gatsby-theme-marble/src/utils/__tests__/test.buildReferalState.js, site/content/configuration.js, site/src/@ndlib/gatsby-theme-marble/assets/i18n/json/common.en.json, site/src/@ndlib/gatsby-theme-marble/assets/i18n/json/text.en.json, site/src/@ndlib/gatsby-theme-marble/components/Pages/IndexPage/index.js, site/src/@ndlib/gatsby-theme-marble/components/Shared/SearchTools/SearchFilterBox/index.js, site/src/@ndlib/gatsby-theme-marble/components/Shared/SearchTools/SearchFilterBox/test.js
Here are a few more examples of translations.
=> MARBLE-890 i18n Translations (part 2)

@ndlib/gatsby-theme-marble/src/components/App/Pages/User/LogOut/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/LoginArea/OktaLogin/index.js, @ndlib/gatsby-theme-marble/src/store/actions/loginActions/index.js
These should be the minimal changes to get Okta login working again.
=> MARBLE-877 Fix Okta 2.x to 3.x changes

scripts/gatsby-source-iiif/getSchema.js
* Add a retry limit and retry failed fetch attempts a couple of times before giving up and moving on. 
* Print out an error listing of failed items.
=> Quick fix for fetching nd.json

site/src/@ndlib/gatsby-theme-marble/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadCitation/index.js, site/src/@ndlib/gatsby-theme-marble/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadCitation/test.js
Added date to Snite citation generation.
=> Quick fix to citation generator

@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/AddNewPortfolio/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/BookmarkButton/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadImage/ImagePreview/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadImage/ImagePreview/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadImage/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadImage/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadImage/utils.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadMetadata/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/index.js, site/src/pages/sitemap.js
* MARBLE-975 `ActionButtonGroup` component and sub components
* MARBLE-959 `/sitemap` page
=> MARBLE-975, MARBLE-959 Action Buttons and Sitemap page

@ndlib/gatsby-theme-marble/package.json, @ndlib/gatsby-theme-marble/src/components/Pages/MiradorViewer/MiradorWrapper/index.js, @ndlib/gatsby-theme-marble/src/components/Pages/MiradorViewer/index.js, yarn.lock
=> MARBLE-828 add rotation to mirador

@ndlib/gatsby-theme-marble/src/components/Internal/MetaDataList/MetaDataField/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/test.js
* Update`ManifestCard` component to search MarbleItem
* Unskip unit test for `ManifestCard`
* Fix other failing unit test
=> MARBLE-956 update ManifestCard

@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchAdditionalTools/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/Pager/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/Pager/sx.js
=> MARBLE-916 display number of search results

@ndlib/gatsby-theme-marble/gatsby-node.js, @ndlib/gatsby-theme-marble/src/templates/marbleItem.js, @ndlib/gatsby-theme-marble/src/utils/__tests__/test.citationGenerator.js, @ndlib/gatsby-theme-marble/src/utils/__tests__/test.mapStandardJson.js, @ndlib/gatsby-theme-marble/src/utils/mapStandardJson/citationGenerator.js, @ndlib/gatsby-theme-marble/src/utils/mapStandardJson/index.js
Added citation field on MarbleItems to be generated from metadata. Updated citation tests to reflect work.
=> MARBLE-998 Citation field generation

@ndlib/gatsby-theme-marble/src/components/Internal/Link/index.js, site/src/@ndlib/gatsby-theme-marble/components/Pages/ExhibitsPage/index.js, site/src/pages/exhibits.js
Title changed to "Digital Exhibits" , updated description, and exhibits now open in new tab.
=> MARBLE-978 Update digital exhibits page

@ndlib/gatsby-theme-marble/src/assets/css/global.css, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/index.js, @ndlib/gatsby-theme-marble/src/templates/marbleItem.js, @ndlib/gatsby-theme-marble/src/utils/__tests__/test.makeMetadataArray.js
* Fix placement of previous/next buttons on Mirador.
* Fix failing unit test
* Fix graphQL query
=> MARBLE-1013 Mirador next/previous button placement

@ndlib/gatsby-theme-marble/src/components/Shared/Card/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/Card/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/index.js
Search terms to be highlighted in Title and Creator as well as metadata
=> MARBLE-1008 Highlight all search terms

tests/postman/README.md, tests/postman/collection.json
Just a simple smoke test that gives something to run in a CI/CD pipeline.
=> Add smoke test

@ndlib/gatsby-theme-marble/src/components/App/FormElements/ImageSelect/index.js, @ndlib/gatsby-theme-marble/src/components/App/FormElements/RadioList/index.js, @ndlib/gatsby-theme-marble/src/components/Internal/DisplayViewToggle/DisplayViewToggleInternal/ToggleButton/index.js, @ndlib/gatsby-theme-marble/src/components/Internal/ShareButton/ShareModalContent/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/AddNewPortfolio/index.js
MARBLE-1065 add label attributes to inputs to improve accessibility
=> Add labels

@ndlib/gatsby-theme-marble/src/components/Internal/MetaDataList/MetaDataField/MetaDataSearchValue/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/BrowseBar/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/BrowseBar/sx.js, site/src/@ndlib/gatsby-theme-marble/components/Pages/BrowsePage/index.js, site/src/@ndlib/gatsby-theme-marble/components/Pages/IndexPage/index.js, site/src/@ndlib/gatsby-theme-marble/components/Pages/IndexPage/sx.js
Browse band, browse categories, and link fixes applied, as well as 
removal of block quote
=> MARBLE-1092,1093,1094

@ndlib/gatsby-theme-marble/src/components/Shared/Card/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/Card/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/Image/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/Image/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/ManifestCardChildren/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/ManifestCardChildren/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/test.js
* Make ManifestCard actually use the local static image correctly.
* Separate ManifestCard into some smaller components.
* Fix tests
* Remove some debugging stuf that is no longer valid.
=> Fix manifest cards

@ndlib/gatsby-theme-marble/gatsby-node.js, @ndlib/gatsby-theme-marble/src/components/Internal/MetaDataList/MetaDataField/MetaDataSearchValue/index.js, @ndlib/gatsby-theme-marble/src/components/Internal/MetaDataList/MetaDataField/index.js, @ndlib/gatsby-theme-marble/src/components/Pages/Search/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchFilterBox/index.js, @ndlib/gatsby-theme-marble/src/templates/marbleItem.js, @ndlib/gatsby-theme-marble/src/utils/mapStandardJson/makeMetadataArray.js, scripts/gatsby-source-iiif/getSchema.js, scripts/gatsby-source-iiif/indexSearch.js, scripts/gatsby-source-iiif/src/getCreators/index.js, scripts/gatsby-source-iiif/src/getCreators/test.js
Updated the search to do a faceted search on the creator, contributor, and subjects.
=> update the search lists

@ndlib/gatsby-theme-marble/src/utils/__tests__/test.mapImageMetadata.js, @ndlib/gatsby-theme-marble/src/utils/mapStandardJson/imageMetadata.js
* Be able to find more local pictures.
=> Fix for image names

@ndlib/gatsby-theme-marble/src/components/Internal/MetaDataList/MetaDataField/index.js, @ndlib/gatsby-theme-marble/src/components/Internal/MetaDataList/MetaDataField/test.js, @ndlib/gatsby-theme-marble/src/components/Pages/Search/index.js, @ndlib/gatsby-theme-marble/src/utils/mapStandardJson/makeMetadataArray.js, scripts/gatsby-source-iiif/indexSearch.js
Fix the collecton facet
add mailto to contact us. 
Fix metadata fields with no values.
=> A couple Metadata fixes

@ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ItemAlternateViews/AlternateImage/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ItemAlternateViews/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/test.js, @ndlib/gatsby-theme-marble/src/utils/__tests__/test.findImage.js, @ndlib/gatsby-theme-marble/src/utils/findImage.js
* Make the Item page images use the local image when possible
* Write/update unit tests
=> MARBLE-1097 Use local images for item page.

@ndlib/gatsby-theme-marble/src/assets/icons/svg/check_box-24px.svg, @ndlib/gatsby-theme-marble/src/assets/icons/svg/check_box_outline_blank-24px.svg, @ndlib/gatsby-theme-marble/src/components/Pages/Search/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchRefinementListFilter/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchRefinementListFilter/sx.js
* More link uses theme color
* Checkboxes use material icons because theming bemblocks is horrible.
=> MARBLE-1100 Make Searchkit match site style

@ndlib/gatsby-theme-marble/src/components/Internal/DisplayViewToggle/DisplayViewToggleInternal/sx.js, site/src/@ndlib/gatsby-theme-marble/components/Layout/PageWrapper/NavigationHeader/DefaultHeader/sx.js
MARBLE-1125, 1126. Fix display of dropdown menu, fix visual of view toggle buttons
=> MARBLE-1125, 1126 fix dropdown menu, view toggle buttons

@ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/ManifestCardChildren/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestCard/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchFilterBox/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/index.js, scripts/gatsby-source-iiif/indexSearch.js
A couple of changes.
Change the search to have a filtered field that uses the ascii folded filter which removes diacritics from the text and the search for comparison. 
Changed the id in elastic search. 
Changed how we identify fields in the highlights.   The new field name has a dot in it so I had to use strings and []
=> update the fields and search to use the folded search field

@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchFilterBox/index.js, scripts/gatsby-source-iiif/indexSearch.js
This PR feels pretty anti-climatic considering what I was doing to try to get this to work yesterday...
=> add quotes into the search

@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/index.js, scripts/gatsby-source-iiif/indexSearch.js
and the ids from all pool because you can find them in the main search
=> remove leading zeros from the id search. 

@ndlib/gatsby-theme-marble/gatsby-node.js, @ndlib/gatsby-theme-marble/src/components/Pages/MarbleItem/ItemLayout/index.js, @ndlib/gatsby-theme-marble/src/components/Pages/MarbleItem/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ItemAlternateViews/AlternateImage/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ItemAlternateViews/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ItemAlternateViews/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/test.js, @ndlib/gatsby-theme-marble/src/templates/marbleItem.js, @ndlib/gatsby-theme-marble/src/utils/__tests__/test.findImage.js, @ndlib/gatsby-theme-marble/src/utils/findImage.js, scripts/gatsby-source-iiif/downloadImages.js, scripts/gatsby-source-iiif/getImageInfo.js, site/src/pages/image-test.js
=> MARBLE-1120 Pull all the images

site/src/@ndlib/gatsby-theme-marble/components/Layout/PageWrapper/NavigationHeader/DefaultHeader/sx.js, site/src/@ndlib/gatsby-theme-marble/components/Layout/PageWrapper/NavigationHeader/HomeHeader/sx.js
=> Header sx fix

@ndlib/gatsby-theme-marble/src/components/App/FormElements/RadioList/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/Portfolio/PortfolioBody/PortfolioEditSettings/PortfolioSettingsContent/DangerDelete/index.js
There were annoying me while tracking down an error. Two fixes:
* Fix missing `key` attribute in RadioList
* Fix unused variables in `DangerDelete` component
=> Two quick linting and unit test error log fixes

@ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserBody/PortfolioList/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserBody/PortfolioList/style.module.css
Add delete button to portfolio list page
=> MARBLE-1035 add portfolio delete button

@ndlib/gatsby-theme-marble/src/components/Shared/Card/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/Card/sx.js
improve UX by changing position of external link relative to image
=> MARBLE-1123 Shift external link placement

@ndlib/gatsby-theme-marble/src/assets/css/global.css, @ndlib/gatsby-theme-marble/src/components/App/FormElements/RadioList/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/Portfolio/PortfolioBody/PortfolioItems/Item/EditItemForm/EditItemFormContent/SetPortfolioImage/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/Portfolio/PortfolioBody/PortfolioItems/Item/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/Portfolio/PortfolioBody/PortfolioItems/Item/sx.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserBasePath/UserBasePathContent/CreateAccount/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserBody/PortfolioList/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserBody/UserEdit/index.js, @ndlib/gatsby-theme-marble/src/components/Internal/MetaDataList/MetaDataField/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/BookmarkButton/index.js, site/.env.development
* Fix api endpoint for user content local testing
* Fix broken radio buttons
* Fix `valid` on email fields
* Various linting things
=> Various fixes

site/content/menus.js, site/src/@ndlib/gatsby-theme-marble/components/Layout/PageWrapper/Footer/index.js, site/src/@ndlib/gatsby-theme-marble/components/Layout/PageWrapper/Footer/sx.js
PO asked for some minor fixes to footer
=> Quick fixes to footer

scripts/gatsby-source-iiif/indexSearch.js
=> index all the STUFF

@ndlib/gatsby-theme-marble/src/components/Internal/MetaDataList/index.js, @ndlib/gatsby-theme-marble/src/components/Internal/MetaDataList/style.module.css, site/src/@ndlib/gatsby-theme-marble/components/Pages/MarbleItem/ItemLayout/index.js, site/src/@ndlib/gatsby-theme-marble/components/Pages/MarbleItem/ItemLayout/sx.js
=> MARBLE-1259, 1260, 1261, 1262 Layout CSS Changes

README.md, scripts/codebuild/install.sh
Partial update to instructions came in a previous PR. This should be all the changes for someone to be able to build, run, and test locally.
=> MARBLE-1171 Update README build instructions

@ndlib/gatsby-theme-marble/src/components/Internal/BackToItem/index.js, @ndlib/gatsby-theme-marble/src/components/Internal/ReturnToSearch/index.js
=> MARBLE-1284 fix return arrow alignment

@ndlib/gatsby-theme-marble/src/components/App/Pages/User/UserBody/PortfolioList/index.js
Add confirmation window for deletion of a portfolio
=> MARBLE-1281 Confirm deletion of portfolio

@ndlib/gatsby-starter-marble/content/configuration.js, site/content/configuration.js
=> MARBLE-1264 Inquisition setup and further cleanup

@ndlib/gatsby-theme-marble/src/components/Pages/MarbleItem/RelatedItemsFromSearch/index.js, @ndlib/gatsby-theme-marble/src/components/Pages/MarbleItem/index.js
* Update Inquisition and fix the related search feature when there is no 
search index.
=> Related Search quick fix

site/src/@ndlib/gatsby-theme-marble/components/Pages/MarbleItem/ItemLayout/index.js
=> Add library identifiers to the access information box

site/src/@ndlib/gatsby-theme-marble/components/Pages/MarbleItem/ItemLayout/index.js
=> Remove URI Value from object page

@ndlib/gatsby-theme-marble/src/components/App/Pages/Portfolio/PortfolioBody/index.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/Portfolio/PortfolioBody/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchBox/SearchField/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchBox/index.js
=> MARBLE-1326 add Search box on portfolio page

@ndlib/gatsby-theme-marble/src/components/App/Pages/Portfolio/PortfolioBody/index.js
fixes search issue with MARBLE-1326
=> include location in searchbox

site/src/@ndlib/gatsby-theme-marble/components/Pages/MarbleItem/ItemLayout/index.js
=> MARBLE-1288 Move action buttons below image

@ndlib/gatsby-theme-marble/src/components/App/Pages/Portfolio/PortfolioBody/PortfolioItems/EditList/SortableItem/sx.js, @ndlib/gatsby-theme-marble/src/components/App/Pages/Portfolio/PortfolioBody/sx.js, sites/marble/src/gatsby-plugin-theme-ui/index.js
MARBLE-1332: Fix public/private flag opacity issue
MARBLE-1333: Set portfolio's sort fonts to be same as portfolio's view fonts
Fix spacing of grey around portfolio search
=> Minor Fixes to UI

@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadImage/index.js
=> MARBLE-1339 Change text on unavailable download due to Copyrighted image

@ndlib/gatsby-theme-marble/src/utils/mapStandardJson/makeMetadataArray.js
=> MARBLE-1342 Add related location to metadata for Snite

@ndlib/gatsby-theme-marble/src/assets/images/pdf.svg, @ndlib/gatsby-theme-marble/src/components/Shared/ChildManifests/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/test.js, @ndlib/gatsby-theme-marble/src/utils/__tests__/test.findImage.js, @ndlib/gatsby-theme-marble/src/utils/findImage.js, yarn.lock
* Show PDF icon when no image is found on item and collection pages
* Update unit tests
=> MARBLE-1296 Show PDF icon on page level

@ndlib/gatsby-theme-marble/src/components/Internal/MetaDataList/index.js
=> MARBLE-1374 Remove 'URI Value' from metadata list

@ndlib/gatsby-theme-marble/src/components/Internal/Seo/DataLayer/index.js, @ndlib/gatsby-theme-marble/src/components/Internal/Seo/index.js
This is a test that looks for the window object and pushes metaData to it on componentDidMount.  This is to determine if tag manager can reach the data
=> Added dataLayer

@ndlib/gatsby-theme-marble/src/components/Internal/Seo/DataLayer/index.js
added event to trigger data push
=> updated dataLayer with event

@ndlib/gatsby-starter-marble/package.json, @ndlib/gatsby-theme-marble/package.json, yarn.lock
See also:
* https://github.com/ndlib/marble-web/pull/32
* https://github.com/ndlib/inquisition/pull/9
=> Update to gatsby 2.32.4

@ndlib/gatsby-theme-marble/src/components/Internal/MetaDataList/MetaDataField/MetaDataLabel/index.js, @ndlib/gatsby-theme-marble/src/components/Internal/MetaDataList/MetaDataField/MetaDataLabel/sx.js, @ndlib/gatsby-theme-marble/src/components/Internal/MetaDataList/MetaDataField/MetaDataLabel/test.js
=> MARBLE-1398 Pad metatadata titles to align to values

@ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ViewerLink/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ViewerLink/test.js
MARBLE-1423 Update Image Viewer modal to use fullscreen Action Modal
=> Set Image Viewer to look like other modals

@ndlib/gatsby-source-appsync-marble-standard/gatsby-node.js, @ndlib/gatsby-source-appsync-marble-standard/package.json, @ndlib/gatsby-source-appsync-marble-standard/src/getItems.js, @ndlib/gatsby-source-appsync-marble-standard/src/getListOfItems.js, @ndlib/gatsby-source-appsync-marble-standard/src/macDNS.js, @ndlib/gatsby-source-appsync-marble-standard/src/queryFile.js, @ndlib/gatsby-source-appsync-marble-standard/src/queryItem.js, @ndlib/gatsby-source-appsync-marble-standard/src/queryWebsite.js, @ndlib/gatsby-source-appsync-marble-standard/src/writeDebug.js, @ndlib/gatsby-transformer-marbleitem/gatsby-node.js, @ndlib/gatsby-transformer-marbleitem/src/crawlStandardJson/crawlAppSyncFiles.js, @ndlib/gatsby-transformer-marbleitem/src/crawlStandardJson/index.js, @ndlib/gatsby-transformer-marbleitem/src/mapStandardJson/fileMetadata.js, @ndlib/gatsby-transformer-marbleitem/src/mapStandardJson/index.js, yarn.lock
These changes should not affect anything until this is also merged: https://github.com/ndlib/marble-web/pull/38
=> MARBLE-1412, 1413, 1414, 1415 GraphQl Source and Transformer plugin changes.

@ndlib/gatsby-source-appsync-marble-standard/src/getItems.js, @ndlib/gatsby-source-appsync-marble-standard/src/queryItem.js, @ndlib/gatsby-transformer-marbleitem/src/mapStandardJson/fileMetadata.js, scripts/gatsby-source-iiif/setupEnv.js
fix some graphql changes upstream
rename variables
=> GraphQl sourcing changes

@ndlib/gatsby-source-appsync-marble-standard/gatsby-node.js, @ndlib/gatsby-source-appsync-marble-standard/package.json, @ndlib/gatsby-source-appsync-marble-standard/src/getItems.js, @ndlib/gatsby-transformer-marbleitem/src/crawlStandardJson/crawlAppSyncFiles.js, yarn.lock
* Fix missing files
* Add progress bar to download in Item harvest
**Note**
* Rerun `yarn` as a new dependency has been added to the source plugin.
=> MARBLE-1413 file fixes

@ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ViewerLink/index.js
* Fix fullscreen
* Fix padding
=> MARBLE-1471 Fix mirador fullscreen bug

CONTRIBUTING.md
=> Add contributing.md to main repo

@ndlib/gatsby-theme-marble/src/assets/theme.js
This overwrites the colors of primary on the cards.
=> fix the card color by default

@ndlib/gatsby-theme-marble/src/components/Shared/CardGroup/CardGroupToggle/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/CardGroup/CardGroupToggle/sx.js, yarn.lock
When I started this I used the grid a bit more than I should. 
Changed to flex with space between to separate the boxes.
=> fixes layout bug with the small card groups over lapping

@ndlib/gatsby-source-appsync-marble/src/getItems/index.js, @ndlib/gatsby-source-appsync-marble/src/getItems/queryItem.js, @ndlib/gatsby-source-appsync-marble/src/getItems/transform/transformAndCreateFile.js, @ndlib/gatsby-theme-marble/src/components/Pages/MarbleItem/ItemLayout/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/DownloadModalContent/DownloadPdf/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionModal/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ViewerLink/ViewerContent/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ViewerLink/index.js
* Fix layout on top of item page
* Detect PDFs and show them in native PDF viewer
* Fixes for file transformation to make MarbleFiles work correctly
=> MARBLE-1365, 1525 PDF Viewer and MarbleItem layout top fix

@ndlib/gatsby-source-appsync-marble/src/getItems/transform/transformAndCreateFile.js
* Update transformAndCreateFile.js
=> Temporary fix for PDFs which are now served at HTTPS urls.

@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/HitResult/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/HitResult/test.js
MARBLE-1469 Appending missing highlight field data back into returned display data.
=> fix search highlight error

@ndlib/gatsby-source-appsync-marble/src/getItems/index.js, @ndlib/gatsby-source-appsync-marble/src/getItems/transform/merge.js
Create plugin option to merge two items together. Right now this is somewhat opinionated and only applies to the Jazz programs, but hopefully this is generic enough that we can expand on it in the cases of other special cases.
See also: https://github.com/ndlib/marble-web/pull/49
=> MARBLE-1545 Prune and Merge Layers for Jazz Programs

@ndlib/gatsby-theme-marble/src/components/Shared/Seo/SeoContent/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/Seo/SeoContent/test.js
hot fix to unfurl image in slack
=> changed OG image to point to thumbnail size

@ndlib/gatsby-theme-marble/src/components/Shared/Seo/SeoContent/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/Seo/SeoContent/test.js
added secondary image to openGraph
=> Marble1597

@ndlib/gatsby-theme-marble/gatsby-config.js
See also: https://github.com/ndlib/marble-web/pull/57
=> MARBLE-1543 Featured Landing Page Mockup

@ndlib/gatsby-theme-marble/src/components/Shared/MetaDataList/MetaDataField/MetaDataAidValue/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/MetaDataList/MetaDataField/MetaDataAidValue/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/MetaDataList/MetaDataField/index.js
MARBLE-1639 Have links to Aleph and ASpace open into a new window.
=> Link finding aid to new tab

@ndlib/gatsby-theme-marble/src/components/Shared/NDBrand/Header/NavSearch/index.js
MARBLE-1688 make sure when search box is selected, entire box is highlighted
=> fix search box border

@ndlib/gatsby-theme-marble/src/components/Shared/MarbleItem/ItemLayout/TombstoneMetadata/TombstoneField/index.js
MARBLE-1648, encodeURI function does not include encoding ampersand, added additional coding.
=> Add ampersand encoding

@ndlib/gatsby-source-appsync-marble/src/getItems/transform/makeMetadataArray/index.js, @ndlib/gatsby-theme-marble/src/assets/css/global.css, @ndlib/gatsby-theme-marble/src/components/Shared/NDBrand/Layout/index.js, @ndlib/gatsby-theme-marble/src/utils/__tests__/test.makeMetadataArray.js, @ndlib/gatsby-theme-marble/src/utils/mapStandardJson/makeMetadataArray.js, @ndlib/gatsby-transformer-marbleitem/src/mapStandardJson/makeMetadataArray.js, yarn.lock
remove white space on the right of the site. 
remove university of nd from display text
=> 2 small changes

@ndlib/gatsby-theme-marble/src/assets/i18n/json/text.default.en.json
* PO Would like update to portfolio layout settings language
=> MARBLE-1733 Update layout setting description

@ndlib/gatsby-theme-marble/src/assets/css/global.css, @ndlib/gatsby-theme-marble/src/assets/theme.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/ActionButton/style.module.css, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/AddNewPortfolio/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/BookmarkButton/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionModal/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/Card/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/FormElements/TextArea/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/FormElements/TextField/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ViewerLink/ViewerContent/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/NDBrand/Drawer/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/NDBrand/Header/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/NDBrand/Layout/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchRefinementListFilter/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/ShareButton/ShareModalContent/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/SkipToMain/__snapshots__/test.js.snap, @ndlib/gatsby-theme-marble/src/components/Shared/SkipToMain/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SkipToMain/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/UserCartouche/index.js
1.  Changed it so the tab order starts on the menu
2. Added aria-hidden to different elements to show what is focused.  
3. Added a return to focus of the menu button when it is closed 
4. Removed all the outline: 0/none since this should generally never be set. 
5. fixed the mirador viewer's not displaying.
=> Accessibility work on the main menu

@ndlib/gatsby-source-appsync-marble/src/getItems/transform/citationGenerator/index.js
MARBLE-1729 fix Artist showing in creator section on museum page citations.
=> add a check on creators object

@ndlib/gatsby-theme-marble/src/components/Shared/ParentLink/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SiblingItems/index.js
=> Marble1809

@ndlib/gatsby-theme-marble/src/components/Shared/Seo/SeoContent/HubJsonLd/__snapshots__/test.js.snap, @ndlib/gatsby-theme-marble/src/components/Shared/Seo/SeoContent/HubJsonLd/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/Seo/SeoContent/HubJsonLd/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/Seo/SeoContent/SchemaJsonLd/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/Seo/SeoContent/SchemaJsonLd/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/Seo/SeoContent/index.js
This adds a "CollectionPage" structural data script to the "Hub" pages (i.e. featured portfolios)
=> Marble1713

@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/DropDown/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/DropDown/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/NDBrand/Header/NavSearch/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchBox/SearchButton/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchBox/SearchField/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchBox/index.js
Updates to the Portfolio button to improve VO navigation with the keyboard as well as improvements to the Search input (which addresses some issues in [Marble1766](https://jira.library.nd.edu/browse/MARBLE-1766))
=> Marble1769

@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/DownloadButton/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ViewerLink/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ShareButton/index.js
This adds aria-modal to specific modal instances that have exit mechanisms
[Marble1764](https://jira.library.nd.edu/browse/MARBLE-1764)
[Aria-modal-update](https://github.com/ndlib/marble-web/compare/aria-modal-update?expand=1)
=> Marble1764

@ndlib/gatsby-theme-marble/src/components/Shared/BrowseBar/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ItemAlternateViews/AlternateImage/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/ItemAlternateViews/AlternateImage/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ManifestImageGroup/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/Seo/helpers.js, @ndlib/gatsby-theme-marble/src/components/Shared/Seo/test.js
This ticket addresses the image alt and title tags on the object page. Where we have a description of the object, we add that as the alt text. Where we do not have a description but have a classification, we generate an alt text that utilizes the classification and title props: ex. 'This is a **painting** called '**Mona Lisa**'. Where we have neither a description or a classification the alt text will read: 'Open in external viewer application'
=> alt text for object and alternative images and unit tests

@ndlib/gatsby-source-appsync-marble/src/getItems/transform/getIiif/index.js, @ndlib/gatsby-source-appsync-marble/src/getItems/transform/getIiif/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/DisplayCard/CardImage/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/DisplayCard/CardImage/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/DisplayCard/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/Image/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/Image/test.js, @ndlib/gatsby-theme-marble/src/utils/__tests__/test.fileMetadata.js, @ndlib/gatsby-theme-marble/src/utils/mapStandardJson/fileMetadata.js, @ndlib/gatsby-transformer-marbleitem/src/mapStandardJson/fileMetadata.js
* Fix handling of missing images on `DisplayCard`
* Resize thumbnails from `!250,250` to `!300,300`
=> DisplayCard image fix

@ndlib/gatsby-theme-marble/src/components/Shared/NDBrand/Header/index.js
* Hide subtitle if titleOverride is passed
=> MARBLE-1736 Inquistion Logo change

@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/AddNewPortfolio/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/AddNewPortfolio/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/AddNewPortfolio/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/BookmarkButton/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/BookmarkButton/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/BookmarkButton/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/DropDown/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/DropDown/test.js, yarn.lock
* Fix style
* Fix data mapping
* Update and add unit tests
=> MARBLE-1894 Fix Bookmark button on Cards

@ndlib/gatsby-source-appsync-marble/src/getItems/transform/makeMetadataArray/index.js, @ndlib/gatsby-theme-marble/src/utils/mapStandardJson/makeMetadataArray.js
This code is duplicated (for reasons™️) and need to be changed in more than one place.
This should complete this PR: https://github.com/ndlib/marble-website-starter/pull/603
=> MARBLE-1734 Users would like the Genre/Physical Characteristics Facetable

@ndlib/gatsby-theme-marble/src/utils/api.js, scripts/codebuild/codebuild.sh, scripts/environment-configuration/setupEnv.js
fixies a problem where the api was using the same api for test and prod.
=> fix the api to use the keys in the env

@ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchRefinementListFilter/sx.js
An update of the facet text colors to be WCAG AAA compliant
=> Marble1951

@ndlib/gatsby-theme-marble/src/components/Shared/Seo/SeoContent/HubJsonLd/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/Seo/SeoContent/SchemaJsonLd/index.js
changed materialType from Library Collection to Collection
=> Marble1953

@ndlib/gatsby-source-appsync-marble-inquisition/src/getItems/transform/searchData/getGeographicLocations/index.js
Aleph and AS look different.
This fixes the aleph case simplistically.
=> normalize geolocation in search facet

@ndlib/gatsby-theme-marble/src/components/Shared/NDBrand/Hero/Default/sx.js
=> MARBLE-2021 Fix "Browse Collection" button

@ndlib/gatsby-source-appsync-marble-inquisition/src/getItems/transform/index.js
Reverts ndlib/marble-website-starter#648
=> Revert "MARBLE-2036 INQ numbers in slug"

@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/sx.js
Fixes visibility of feedback button when over portfolio button
=> removed zindex from BookmarkGroup

@ndlib/gatsby-plugin-marble-elasticsearch/gatsby-node.js, @ndlib/gatsby-plugin-marble-elasticsearch/package.json, @ndlib/gatsby-plugin-marble-elasticsearch/src/setupIndex.js, @ndlib/gatsby-theme-marble/gatsby-node.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchBase/index.js, yarn.lock
Changes to use OpenSearch instead of ElasticSearch. Requires new environment variables.
See also:
* Inquisition: https://github.com/ndlib/inquisition/pull/85
* Marble: https://github.com/ndlib/marble-web/pull/139
=> Changes to use Opensearch

@ndlib/gatsby-theme-marble/src/utils/api.js, scripts/codebuild/codebuild.sh, scripts/environment-configuration/setupEnv.js, scripts/preload-env.sh, scripts/setup-development.sh
See also: 
* https://github.com/ndlib/marble-web/pull/140
* https://github.com/ndlib/inquisition/pull/86
=> Update environment variables

@ndlib/gatsby-theme-marble/src/utils/api.js, scripts/codebuild/codebuild.sh, scripts/environment-configuration/setupEnv.js, scripts/preload-env.sh, scripts/setup-development.sh
Reverts ndlib/marble-website-starter#659
=> Revert "Update environment variables"

.github/workflows/ci.yml, @ndlib/gatsby-source-appsync-marble-inquisition/src/getItems/index.js, @ndlib/gatsby-theme-marble/src/store/actions/loginActions/index.js, @ndlib/gatsby-theme-marble/src/utils/api.js, scripts/codebuild/codebuild.sh
See also:
* https://github.com/ndlib/marble-web/pull/142
=> Environment variable changes

yarn.lock
Reverts ndlib/marble-website-starter#669
=> Revert "Bump simple-get from 3.1.0 to 3.1.1"

@ndlib/gatsby-theme-marble/package.json, yarn.lock
Reverts ndlib/marble-website-starter#676
=> Revert "Bump moment from 2.29.1 to 2.29.4"

yarn.lock
Reverts ndlib/marble-website-starter#671
=> Revert "Bump minimist from 1.2.5 to 1.2.6"

@ndlib/gatsby-theme-marble/src/components/Shared/ChildManifests/Pager/PagerButton/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ChildManifests/Pager/PagerSeries/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ChildManifests/Pager/ShowAll/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ChildManifests/Pager/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ChildManifests/index.js
* On collection level pages with more than 30 items a pager will appear.
* `?p=0` will display all items
=> MARBLE-2106 Paginate Collection pages

@ndlib/gatsby-source-appsync-marble-inquisition/src/getItems/transform/formatSearchData/index.js, @ndlib/gatsby-source-appsync-marble/src/getItems/transform/formatSearchData/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchFilterBox/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/HitDisplay/HitResult/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/SearchTools/SearchResults/searchSettings.js
This makes search work better for unique identifiers.
**See also:**
https://github.com/ndlib/marble-web/pull/155
https://github.com/ndlib/inquisition/pull/92
=> MARBLE-2099 Additional changes to search for identifiers

@ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/AddNewPortfolio/index.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/AddNewPortfolio/sx.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/BookmarkOptions/AddNewPortfolio/test.js, @ndlib/gatsby-theme-marble/src/components/Shared/ActionButtonGroup/BookmarkGroup/sx.js
* Fixes some alignment, and color issues with the popup for adding items to portfolios
* Stops link propagation correctly again (clicking add/remove no longer triggers the link behind it)
* fix unit test
=> MARBLE-2113 Fix add to portfolio on item cards

scripts/environment-configuration/package.json, scripts/environment-configuration/setupEnv.js, scripts/environment-configuration/yarn.lock
=> Upgrade aws sdk
